image:
  file: .gitpod.Dockerfile

tasks:
  # - init: 'echo "TODO: Replace with init/build command"'
  - before: npm install -g expo-cli
  #- before: cd server
  #  command: npm install && npm run dev    
